---
#create batch users add password or update and keyfile
- name: Ucreate user sudo
  hosts: test
  become: true
  tasks:
    - name: Install Fail2Ban package
      apt:
        name: fail2ban
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Fail2Ban package
      yum:
        name: fail2ban
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start Fail2Ban service
      systemd:
        name: fail2ban
        state: started
        enabled: yes


