---
#CreateCT
- name: create ct
  hosts: localhost
  become: true
  vars_files:
    - ./vars/proxmox_var_dev.yaml
    - - ../passwd.yml
  tasks: 
    - name: Prompt for hostname
      prompt:
        echo: yes
        name: "hostname"
        prompt: "Enter Hostname:"
      register: hostname_prompt
    - name: Deploy proxmox
      proxmox:
        api_host: '10.153.12.20' # required. the host of the Proxmox VE cluster
        api_user: "{{ proxdev_user }}" # required. the user to authenticate with
        api_password: "{{ proxdev_pass }}" # not required. the password to authenticate with you can use PROXMOX_PASSWORD environment variable
 #       vmid: '888' # not required. the instance id if not set, the next available VM ID will be fetched from ProxmoxAPI. if not set, will be fetched from PromoxAPI based on the hostname
 #       validate_certs: no # not required. enable / disable https certificate verification
        node: proxmox-devex-1 # not required. Proxmox VE node, when new VM will be created required only for C(state=present) for another states will be autodiscovered
 #       pool:  # not required. Proxmox VE resource pool
        password: '{{ proxdev_temp_pass }}' # not required. the instance root password required only for C(state=present)
        hostname: 'Test' # not required. the instance hostname required only for C(state=present) must be unique if vmid is not passed
        ostemplate: "{{ ostemplate.debian }}" # not required. the template for VM creating required only for C(state=present)
        disk: "{{ storage }}:20" # not required. hard disk size in GB for instance
        cores: 1 # not required. Specify number of cores per socket.
        cpus: 4 # not required. numbers of allocated cpus for instance
        memory: 512 # not required. memory size in MB for instance
        swap: 512 # not required. swap memory size in MB for instance
        netif: '{"net0":"name=eth0,gw=192.168.0.1,ip=192.168.0.2/24,bridge=vmbr0"}' # not required. specifies network interfaces for the container. As a hash/dictionary defining interfaces.
        mounts:  # not required. specifies additional mounts (separate disks) for the container. As a hash/dictionary defining mount points
        ip_address:  # not required. specifies the address the container will be assigned
        onboot: no # not required. specifies whether a VM will be started during system bootup
        storage: '{{ storage }}' # not required. target storage
        cpuunits: 1000 # not required. CPU weight for a VM
        nameserver: '10.153.18.30' # not required. sets DNS server IP address for a container
        searchdomain: gruzef.net # not required. sets DNS search domain for a container
        timeout: 30 # not required. timeout for operations
        force: no # not required. forcing operations can be used only with states C(present), C(stopped), C(restarted) with C(state=present) force option allow to overwrite existing container with states C(stopped) , C(restarted) allow to force stop instance
        state: present # not required. choices: present;started;absent;stopped;restarted. Indicate desired state of the instance
#        pubkey:  # not required. Public key to add to /root/.ssh/authorized_keys. This was added on Proxmox 4.2, it is ignored for earlier versions
        unprivileged: no # not required. Indicate if the container should be unprivileged


