---
#Serch Line and replace
- name: Update sshd_config PasswordAuthentication
  hosts: test
  become: true
  tasks:
    - name: Modify PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        #regexp: '^(Match Address)\s.*\b(PasswordAuthentication\s+)(yes)$'
        regexp: '^(\s*)PasswordAuthentication\s+yes$'
        line: 'PasswordAuthentication no'
        #line: '\1 \2no'
        backup: yes
        state: present
      notify: Restart SSH Service

  handlers:
    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted