---
#create batch users add password or update and keyfile
- name: Ucreate user sudo
  hosts: test
  become: true
  vars:
    username: 
        - name: "test"
          ssh_key: "{{ lookup('file', '/home/dvx-1/Ansible/ssh/dvx-1/public-ssh-devex.pub') }}"
          password: "$6$MF8vSL.qxpqD8.gv$v6n9OeocAxbBQk3rzTChyn4VLgzLMjCkuGyHzYx8fCNZ3qrlYYNtjk1/o1bbjtFokCWQvgPCSSroxn2LoKvR30"
        - name: "sbwork"
          ssh_key: "{{ lookup('file', '/home/dvx-1/Ansible/ssh/dvx-1/public-ssh-devex2.pub') }}"
          password: "$6$dXyyBfurqQztd1kS$Rte0Ft6Cn0gVOO.bdpyfccUXjNGNsy9cDSoGJcb9rsoUdocS54WlYk4XnsYm35Ly/5N2nWFA0lmA6kTYEpPg/1"
#        - name: "test3"
#          ssh_key: "{{ lookup('file', '/home/dvx-1/Ansible/ssh/dvx-1/public-ssh-devex3.pub') }}" 
#          password: "$6$dXyyBfurqQztd1kS$Rte0Ft6Cn0gVOO.bdpyfccUXjNGNsy9cDSoGJcb9rsoUdocS54WlYk4XnsYm35Ly/5N2nWFA0lmA6kTYEpPg/1"    
  tasks:
    - name: Create user "{{ username }}"
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: sudo
        append: yes
        state: present
      with_items: "{{ username }}"
    #add ssh key             
    - authorized_key:
        user: "{{ item.name }}"
        state: present
        manage_dir: yes
        key: "{{ item.ssh_key }}"
      with_items: "{{ username }}"

