---
- name: MemoryCheck
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Distribution
      debug: msg="Distribution:{{ ansible_distribution }} version:{{ ansible_distribution_version}} major:{{ ansible_distribution_major_version }}"
