---
- name: Change PasswordAuthentication setting in sshd
  hosts: all  # Replace with your target host or group
  tasks:
#    - name: Backup sshd config file
#      become: true
#      command: cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
#      ignore_errors: true

    - name: Update PasswordAuthentication setting
      become: true
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        backup: yes

    - name: Restart sshd
      become: true
      service:
        name: sshd
        state: restarted