---
#serch second line after PubkeyAuthentication
- name: Update sshd_config PasswordAuthentication
  hosts: test
  become: true
  tasks:
    - name: Modify PasswordAuthentication #add new line
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config  
        after: 'PubkeyAuthentication'
        regexp: 'PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'
#        regexp: 'port\s+2200'
#        replace: 'port 22'
        backup: yes
#        state: present
      notify: Restart SSH Service

  handlers:
    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted